In [24]:
import cv2 
import os
import shutil
import numpy as np
from matplotlib import pyplot as plt
%matplotlib qt
from tensorflow.keras.models import load_model
import tensorflow as tf

In [2]:
# Active local webcam
camera = cv2.VideoCapture(0)

In [3]:
# Init base variable 
# List to store images from Image Catcher
images = []
# Current file number to save image
file_number = 0
# Get current directory path
current_dir = os.getcwd()
# Check if 'test_iamges' folder exists, if not create folder
if 'test_images' not in os.listdir(path=current_dir):
    os.mkdir('test_images')
    
while True:
    # Get video frame
    _, camera_frame = camera.read()
    # Draw rectangle on catched image - show area of proper photo
    image_with_border = cv2.rectangle(camera_frame, (100, 100), (500, 500), (255,0,0), 2)
    # Show image with drawn border
    cv2.imshow("Image Catcher", image_with_border)
    # Wait for 1[s] to take an action
    pressed_key = cv2.waitKey(1)
    # If 'q' button clicked, exit "Image Catcher"
    if pressed_key == 113:
        print('Exited camera window')
        # Close all opend Windows
        cv2.destroyAllWindows()
        break
    # If 'space' button clicked, take an image
    if pressed_key == 32:
        # Get clear frame (without border)
        _, image = camera.read()
        # Append list with taken image of size 500x500
        images.append(image[100:500, 100:500])     
        # Set path to save taken image
        image_name = f'test_images/testing_image_{file_number}.jpg'
        # Save image 
        cv2.imwrite(image_name, image[100:500, 100:500])
        # Iterate file name by 1
        file_number += 1
        # Print information about saved image
        print("Image saved to list")

Image saved to list
Image saved to list
Image saved to list
Image saved to list
Image saved to list
Image saved to list
Image saved to list
Image saved to list
Image saved to list
Image saved to list
Image saved to list
Image saved to list
Image saved to list
Image saved to list
Exited camera window


In [4]:
# Release used device - built-in camera
camera.release()

In [26]:
predict_emotion = []
predicted_values = []
# Load pretrain model of CNN
model = load_model(os.path.join('models', 'pain_detection_model_VGG16.h5'))
# Loop through images list
for index, img in enumerate(images):
    # Resize image to 256x256 size -> expected size by CNN model
    resized_img = tf.image.resize(img, (224,224))
    # Predict pain image
    predict_emotion.append(model.predict(np.expand_dims(resized_img/255, 0)))
    predicted_values.append(predict_emotion[index][0][0])
    # Show iamges from list in RGB colors
    #cv2.imshow(f'Image_{index}: {predict_emotion[index][0][0]}', img)

# Waiting for key action
cv2.waitKey(0)
# Closing all opend windows with images
cv2.destroyAllWindows()


1/1 [==============================] - 0s 115ms/step


In [79]:
# Print image using matplotlib-pyplot

fig = plt.figure()
len(images)%3 
for i in range(0, len(images)):
    plt.subplot(round(len(images)/4), 4, i+1)
    plt.imshow(cv2.cvtColor(images[i], cv2.COLOR_BGR2RGB))
    plt.gca().set_title('Tested image: %.3f' %predicted_values[i], fontsize=15)

plt.show()

In [58]:
round(len(images)/4)

4

In [29]:

fig_1 = plt.figure()
plt.scatter(np.arange(0, len(predicted_values),1, dtype = int), np.array(predicted_values),  color='teal', marker ='s', label='Value for each image')
plt.plot(np.arange(0, len(predicted_values),1, dtype = int), [0.5 for i in range(len(predicted_values))], color = 'green', label='Dividing line at 0.5', linewidth=2)
fig_1.suptitle('Pain prediction values', fontsize=20)
plt.legend(loc='upper left')
plt.show()

fi_2 = plt.figure()
plt.plot()

[]

In [6]:
predict_emotion

[array([[0.29473516]], dtype=float32),
 array([[0.06853647]], dtype=float32),
 array([[0.13810997]], dtype=float32),
 array([[0.9880064]], dtype=float32),
 array([[0.11388447]], dtype=float32),
 array([[0.9945581]], dtype=float32),
 array([[0.947809]], dtype=float32),
 array([[0.97640914]], dtype=float32),
 array([[0.74176335]], dtype=float32),
 array([[0.43288973]], dtype=float32),
 array([[0.03965661]], dtype=float32),
 array([[0.00608474]], dtype=float32),
 array([[0.02003187]], dtype=float32),
 array([[0.00243415]], dtype=float32)]

In [8]:
# Delete 'test_images' directory after finshed work - optional to use
#shutil.rmtree(os.path.join(current_dir, 'test_images'))
